# Application
spring.application.name=library-management

server.port=8080
server.servlet.context-path=/

## Swagger / OpenAPI
#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.operationsSorter=method

# Logging
logging.level.com.library=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970337336763979244226452948404D6351
jwt.expirationMs=86400000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/lms_db
spring.datasource.username=root
spring.datasource.password=saRan@15

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

